### ISSUE TITLE
Pr's

### ISSUE THREAD

**Issue by sabuto** [CIRCULARKA/InvMan#35]
Just out of interest, I have found this project whilst browsing avalonia projects on github. Are you accepting pr's on this?

**Comment by CIRCULARKA** [comment]
> Just out of interest, I have found this project whilst browsing avalonia projects on github. Are you accepting pr's on this?

**Comment by CIRCULARKA** [comment]
> Just out of interest, I have found this project whilst browsing avalonia projects on github. Are you accepting pr's on this?

Hi, maybe I can figure out what you can help me with, so give me a while

**Comment by CIRCULARKA** [comment]
So yea, I can accept PR's from you made to Avalonia project. Would be gratefull if you'll make some controls like hiddenable text block where you click on a text and it turns into '*' symbols of something like this

**Comment by sabuto** [comment]
> So yea, I can accept PR's from you made to Avalonia project. Would be gratefull if you'll make some controls like hiddenable text block where you click on a text and it turns into '*' symbols of something like this

sure ill do that first :), just so you know i am english though so you may need to translate some things, i see you are using material theme and fluent theme, which do you want the custom controls to conform to?

**Comment by CIRCULARKA** [comment]
To custom controls use material theme. What about russian language in my code - it is my bad because I need to encapsulate messages to user into kind of resources and gather messages from there but there is actually nothing important written in Russian and if you want to show some text to user you can type it on English, i'll just fix the mess with languages later

**Comment by CIRCULARKA** [comment]
And there is one more thing. Custom controls are located at Desktop/InvMan.Desktop.Common/<ControlName>. You can look at other controls there as an examples

**Comment by sabuto** [comment]
ok cool :) as it happens material provide a hideable box you can just do

<TextBox PasswordChar="*" Classes="revealPasswordButton" RevealPassword="True" />

im more than happy to build a custom one but seems silly when material already provides one :)

i can also work on the languages if you like?

**Comment by CIRCULARKA** [comment]
> ok cool :) as it happens material provide a hideable box you can just do
> 
> im more than happy to build a custom one but seems silly when material already provides one :)
> 
> i can also work on the languages if you like?

Oh, idk how I missed that. Yeah, work with langs then

**Comment by CIRCULARKA** [comment]
Can you provide a link to that control?

**Comment by sabuto** [comment]
> Can you provide a link to that control?

https://github.com/AvaloniaCommunity/Material.Avalonia/blob/dev/Material.Styles/TextBox.xaml

it's within here but it's shown in the demo app here

https://github.com/AvaloniaCommunity/Material.Avalonia/blob/dev/Material.Demo/Pages/FieldsDemo.axaml#L40
