### ISSUE TITLE
How to auto generate class from *.resx files

### ISSUE THREAD

**Issue by CIRCULARKA** [CIRCULARKA/InvMan#39]
@sabuto, how did you generated class from ```*.resx``` files? I'm using linux and also have here the ```resgen``` util but it is not allow me to generate class from ```.resx``` files. I see that there some configuration for that process in ```InvMan.Desktop.UI.csproj``` file but this is do not run the process of generation

**Comment by sabuto** [comment]
What ide do you use? I'm using jetbrains rider and it automatically does it for me. If you want you can send me a list of strings you want and I can add them and push?

**Comment by CIRCULARKA** [comment]
> What ide do you use? I'm using jetbrains rider and it automatically does it for me. If you want you can send me a list of strings you want and I can add them and push?

I'm using VSCode and yes, probably there is no such embedded tools. Ok, I'll ping you as I complete translation

**Comment by sabuto** [comment]
OK cool :)

**Comment by CIRCULARKA** [comment]
> OK cool :)

Updated ```resx``` files. Also I changed configuration of auto code generation in ```.csproj``` and hope it'll work fine in your IDE, now ```resx``` files are should be located in ```Localization``` folder. Waiting for your PR

**Comment by sabuto** [comment]
Looks good ill check it later, so what am I pr'ing again?

**Comment by CIRCULARKA** [comment]
> 



> Looks good ill check it later, so what am I pr'ing again?

There was auto generated class called ```Lang.Design.cs```, not I want ```Messages.Design.cs``` (already configured in project file) instead of old version with only one ```Login``` property
